name: talenta-clock-in

on:
  schedule:
    - cron: "00 02 * * 1-5"
    - cron: "30 02 * * 1-5"
    - cron: "00 03 * * 1-5"
    
jobs:
  clock_in:
    runs-on: ubuntu-latest
    env:
      URL_HOME: ${{ secrets.URL_HOME }}
      URL_LIVE_ATTENDANCE: ${{ secrets.URL_LIVE_ATTENDANCE }}
      LATITUDE: ${{ secrets.LATITUDE }}
      LONGITUDE: ${{ secrets.LONGITUDE }}
      EMAIL: ${{ secrets.EMAIL }}
      PASSWORD: ${{ secrets.PASSWORD }}

    steps:
      - name: checkout my app
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: "16.x"
      
      - name: Install dependencies
        run: npm install

      - name: run app
        run: node clock-in.js

